# Generated by Django 4.0.2 on 2022-02-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfest', '0003_persondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payid', models.CharField(max_length=200)),
                ('payuser', models.CharField(max_length=200)),
                ('payemail', models.CharField(max_length=200)),
                ('payaccount', models.CharField(max_length=500)),
            ],
        ),
    ]
